database: mh_admin_vipuser
server:
  port: 9009

spring:
  application:
    name: vip-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  config:
    import:
      - "nacos:datasource"
