### 查询所有订单
GET http://localhost:9003/order


### 远程调用product
GET http://localhost:9003/orders/1

### 远程调用accounts
GET http://localhost:9003/getaccounts/2;



### 远程调用
GET http://localhost:9003/order1/1