server:
  port: 8003

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/member_management?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    port: 6379
#    host: 8.130.75.98