database: mh_user_accounts
server:
  port: 9004

spring:
  application:
    name: accounts-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  config:
    import:
      - "nacos:datasource"
