server:
  port: 10010
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:9003
          order: 0
          predicates: # 断言规则
            - Path=/order/** # 路由order及下所有的路径
        - id: product-service # 路由标识，必须唯一
          uri: http://localhost:9002
          order: 0
          predicates:
            - Path=/getProduct/**