server:
  port: 10010
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
    gateway:
      #网关全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: order-service
          uri: http://localhost:9003
          order: 0
          predicates: # 断言规则
            - Path=/order/** # 路由order及下所有的路径
        - id: product-service # 路由标识，必须唯一
          uri: http://localhost:9002
          order: 0
          predicates:
            - Path=/getProduct/**
        - id: vip-service # 路由标识，必须唯一
          uri: http://localhost:9009
          order: 0
          predicates:
            - Path=/admin/vip/**
        - id: admin-product-service # 路由标识，必须唯一
          uri: http://localhost:9008
          order: 0
          predicates:
            - Path=/admin/product/**
        - id: user-product-service # 路由标识，必须唯一
          uri: http://localhost:9002
          order: 0
          predicates:
            - Path=/user/product/**
        - id: user-car-service # 路由标识，必须唯一
          uri: http://localhost:9010
          order: 0
          predicates:
            - Path=/user/car/**
        - id: user-orders-service # 路由标识，必须唯一
          uri: http://localhost:9003
          order: 0
          predicates:
            - Path=/user/orders/**